/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NativeComment {
  type: 'Line' | 'Block'
  value: string
  start: number
  end: number
}

export interface NativeDiagnostic {
  message: string
  start: number
  end: number
}

export declare function nativeParse(source: string): NativeParseResult

export interface NativeParseResult {
  astJson: string
  sourceType: 'script' | 'module'
  templateTokens: Array<NativeTemplateToken>
  comments: Array<NativeComment>
  irregularWhitespaces: Array<NativeRange>
  errors: Array<NativeDiagnostic>
  panicked: boolean
}

export interface NativeRange {
  start: number
  end: number
}

export interface NativeTemplateToken {
  type: string
  value: string
  start: number
  end: number
}
